<?php

return [
    'commission_rate' => 0.12,
    'payout_delay_hours' => 24,
    'warning_auto_suspend_threshold' => 3,
    'subjects' => [
        'Mathematics',
        'Math',
        'Science',
        'Physics',
        'Chemistry',
        'Biology',
        'English',
        'Hindi',
        'Punjabi',
        'Urdu',
        'Sanskrit',
        'History',
        'Geography',
        'Social Studies',
        'Political Science',
        'Economics',
        'Commerce',
        'Computer Science',
        'Information Technology',
        'Physical Education',
        'Fine Arts',
        'Music',
        'Other',
    ],
    'languages' => [
        'English',
        'Hindi',
        'Punjabi',
        'Bengali',
        'Tamil',
        'Telugu',
        'Marathi',
        'Gujarati',
    ],
    'student_grades' => [
        'Class 1',
        'Class 2',
        'Class 3',
        'Class 4',
        'Class 5',
        'Class 6',
        'Class 7',
        'Class 8',
        'Class 9',
        'Class 10',
        'Class 11',
        'Class 12',
        'Undergraduate',
        'Postgraduate',
    ],
];
